# Generated by Django 3.2.6 on 2021-08-21 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_bio', models.TextField(max_length=500)),
                ('location', models.TextField(help_text='street, city/district, region, country', max_length=300)),
                ('profession', models.CharField(help_text='Profesional Mathematical Teacher', max_length=200)),
                ('employed', models.BooleanField(default=False)),
                ('place_of_employment', models.CharField(blank=True, max_length=250, null=True)),
                ('job_duration', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('seeking_job', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
