# Generated by Django 3.2.6 on 2021-08-21 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_sponsors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sponsors',
            new_name='Sponsor',
        ),
    ]
