# Generated by Django 3.2.6 on 2021-08-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_auto_20210822_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='verified_user',
            field=models.BooleanField(default=False),
        ),
    ]
