# Generated by Django 3.2.6 on 2021-08-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0005_author_verified_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='registered_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
