# Generated by Django 3.2.6 on 2021-08-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0006_author_registered_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='dp',
            field=models.ImageField(blank=True, height_field=100, null=True, upload_to='authors', width_field=100),
        ),
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
