# Generated by Django 3.2.6 on 2021-08-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0007_auto_20210825_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='dp',
            field=models.ImageField(blank=True, height_field='100', null=True, upload_to='authors', width_field='100'),
        ),
    ]
