# Generated by Django 3.2.6 on 2021-08-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0008_alter_author_dp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='dp',
            field=models.ImageField(blank=True, null=True, upload_to='authors'),
        ),
    ]
