# Generated by Django 3.2.6 on 2021-08-25 10:18

import django.core.validators
from django.db import migrations, models
import modules


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0010_alter_author_dp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='dp',
            field=models.ImageField(blank=True, null=True, upload_to='authors', validators=[django.core.validators.validate_image_file_extension, modules.validate_img_extension, modules.validate_image_size]),
        ),
    ]
