# Generated by Django 3.2.6 on 2021-08-26 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0013_alter_sponsor_renewal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
