# Generated by Django 3.2.6 on 2021-08-22 19:53

from django.conf import settings
from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_auto_20210822_1953'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20210822_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_color',
            field=models.CharField(blank=True, choices=[('r', 'danger'), ('s', 'succes'), ('i', 'info')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Full body of the article, supports markup', null=True, verbose_name='Add a body'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='coauthors', to='authors.Author'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='downvotes',
            field=models.ManyToManyField(blank=True, related_name='downvoters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blog',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='upvoters', to=settings.AUTH_USER_MODEL),
        ),
    ]
