# Generated by Django 3.2.6 on 2021-08-23 19:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210822_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='bookmarked_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
