# Generated by Django 3.2.6 on 2021-08-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(default='pi pi-fw pi-angle-double-right', help_text='Icons can be picked from https://www.primefaces.org/primevue/showcase-v2/#/icons', max_length=30),
        ),
    ]
