# Generated by Django 3.2.6 on 2021-08-26 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20210826_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribers',
            name='subscriber_type',
        ),
        migrations.RemoveField(
            model_name='subscribers',
            name='subscription_length',
        ),
    ]
