# Generated by Django 3.2.6 on 2021-08-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20210827_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_color',
            field=models.CharField(blank=True, choices=[('r', 'danger'), ('s', 'success'), ('i', 'info')], max_length=10, null=True),
        ),
    ]
